=== Trollpower/dsa5-discord-bot/schemas/character.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./schemas/character.schema.json",
  "title": "DSA-Bot Character",
  "description": "Pragmatisches JSON Schema für Character-Dateien des DSA-Bot-Projekts.",
  "type": "object",
  "required": [
    "name",
    "eigenschaften",
    "kampftechniken",
    "talente"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "displayName": {
      "type": "string"
    },
    "spieler": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gs": {
      "type": "integer"
    },
    "zk": {
      "type": "integer"
    },
    "sk": {
      "type": "integer"
    },
    "initiative": {
      "type": "integer"
    },
    "alwaysReload": {
      "type": "boolean"
    },
    "cheating": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "general": {
          "type": "number"
        },
        "crit": {
          "type": "number"
        }
      }
    },
    "eigenschaften": {
      "type": "object",
      "required": [
        "MU",
        "KL",
        "IN",
        "CH",
        "FF",
        "GE",
        "KO",
        "KK"
      ],
      "additionalProperties": false,
      "properties": {
        "MU": {
          "type": "integer"
        },
        "KL": {
          "type": "integer"
        },
        "IN": {
          "type": "integer"
        },
        "CH": {
          "type": "integer"
        },
        "FF": {
          "type": "integer"
        },
        "GE": {
          "type": "integer"
        },
        "KO": {
          "type": "integer"
        },
        "KK": {
          "type": "integer"
        }
      }
    },
    "lep": {
      "$ref": "#/$defs/resourceValue"
    },
    "asp": {
      "$ref": "#/$defs/resourceValue"
    },
    "kampftechniken": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/kampftechnik"
      }
    },
    "talente": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/fertigkeitsEintrag"
      }
    },
    "zauber": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/erweiterbareFertigkeit"
      }
    },
    "liturgien": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/erweiterbareFertigkeit"
      }
    },
    "rituale": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/erweiterbareFertigkeit"
      }
    },
    "elfenlieder": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/erweiterbareFertigkeit"
      }
    },
    "zaubermelodien": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/erweiterbareFertigkeit"
      }
    },
    "sonderfertigkeiten": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/namedCategoryEntry"
      }
    },
    "vorteile": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/namedCategoryEntry"
      }
    },
    "nachteile": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/namedCategoryEntry"
      }
    },
    "waffen": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "angelegteWaffen": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ruestungen": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "angelegteRuestung": {
      "type": "string"
    },
    "quickProbeFavorites": {
      "type": "array",
      "maxItems": 3,
      "items": {
        "$ref": "#/$defs/quickProbeFavorite"
      }
    }
  },
  "$defs": {
    "resourceValue": {
      "type": "object",
      "required": [
        "aktuell",
        "max"
      ],
      "additionalProperties": false,
      "properties": {
        "aktuell": {
          "type": "integer"
        },
        "max": {
          "type": "integer"
        }
      }
    },
    "kampftechnik": {
      "type": "object",
      "required": [
        "name",
        "ktw"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "ktw": {
          "type": "integer"
        }
      }
    },
    "fertigkeitsEintrag": {
      "type": "object",
      "required": [
        "name",
        "fertigkeitswert"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "fertigkeitswert": {
          "type": "integer"
        }
      }
    },
    "erweiterbareFertigkeit": {
      "type": "object",
      "required": [
        "name",
        "fertigkeitswert"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "fertigkeitswert": {
          "type": "integer"
        },
        "erweiterungen": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "namedCategoryEntry": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "category": {
          "type": "string"
        },
        "referenz": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "quickProbeFavorite": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/$defs/quickProbeFavoriteProbe"
        },
        {
          "$ref": "#/$defs/quickProbeFavoriteAngriff"
        },
        {
          "$ref": "#/$defs/quickProbeFavoriteKsf"
        }
      ]
    },
    "quickProbeFavoriteProbe": {
      "type": "object",
      "required": [
        "category",
        "name"
      ],
      "properties": {
        "category": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "label": {
          "type": "string"
        },
        "bonusMalus": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "quickProbeFavoriteAngriff": {
      "type": "object",
      "required": [
        "type",
        "waffenName"
      ],
      "properties": {
        "type": {
          "const": "angriff"
        },
        "waffenName": {
          "type": "string",
          "minLength": 1
        },
        "label": {
          "type": "string"
        },
        "bonusMalus": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "quickProbeFavoriteKsf": {
      "type": "object",
      "required": [
        "type",
        "subcommand"
      ],
      "properties": {
        "type": {
          "const": "ksf"
        },
        "subcommand": {
          "type": "string",
          "minLength": 1
        },
        "stufe": {
          "type": "integer"
        },
        "basismanoever": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "bonusMalus": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": true
}

=== Trollpower/dsa5-discord-bot/chars/jalinka.json
{
  "name": "Jalinka",
  "gs": 8,
  "eigenschaften": {
    "MU": 13,
    "KL": 12,
    "IN": 14,
    "CH": 11,
    "FF": 14,
    "GE": 15,
    "KO": 10,
    "KK": 12
  },
  "kampftechniken": [
    {
      "name": "Dolche",
      "ktw": 13
    },
    {
      "name": "Raufen",
      "ktw": 13
    },
    {
      "name": "Schwerter",
      "ktw": 12
    },
    {
      "name": "Wurfwaffen",
      "ktw": 12
    }
  ],
  "talente": [
    {
      "name": "Gaukeleien",
      "fertigkeitswert": 5
    },
    {
      "name": "Klettern",
      "fertigkeitswert": 7
    },
    {
      "name": "Körperbeherrschung",
      "fertigkeitswert": 6
    },
    {
      "name": "Kraftakt",
      "fertigkeitswert": 1
    },
    {
      "name": "Reiten",
      "fertigkeitswert": 5
    },
    {
      "name": "Schwimmen",
      "fertigkeitswert": 5
    },
    {
      "name": "Selbstbeherrschung",
      "fertigkeitswert": 2
    },
    {
      "name": "Sinnesschärfe",
      "fertigkeitswert": 10
    },
    {
      "name": "Taschendiebstahl",
      "fertigkeitswert": 10
    },
    {
      "name": "Verbergen",
      "fertigkeitswert": 10
    },
    {
      "name": "Zechen",
      "fertigkeitswert": 4
    },
    {
      "name": "Betören",
      "fertigkeitswert": 3
    },
    {
      "name": "Gassenwissen",
      "fertigkeitswert": 10
    },
    {
      "name": "Menschenkenntnis",
      "fertigkeitswert": 7
    },
    {
      "name": "Überreden",
      "fertigkeitswert": 9
    },
    {
      "name": "Verkleiden",
      "fertigkeitswert": 2
    },
    {
      "name": "Willenskraft",
      "fertigkeitswert": 4
    },
    {
      "name": "Fesseln",
      "fertigkeitswert": 1
    },
    {
      "name": "Fischen & Angeln",
      "fertigkeitswert": 5
    },
    {
      "name": "Orientierung",
      "fertigkeitswert": 5
    },
    {
      "name": "Wildnisleben",
      "fertigkeitswert": 1
    },
    {
      "name": "Brett- & Glücksspiel",
      "fertigkeitswert": 2
    },
    {
      "name": "Geographie",
      "fertigkeitswert": 2
    },
    {
      "name": "Götter & Kulte",
      "fertigkeitswert": 2
    },
    {
      "name": "Mechanik",
      "fertigkeitswert": 5
    },
    {
      "name": "Rechnen",
      "fertigkeitswert": 4
    },
    {
      "name": "Rechtskunde",
      "fertigkeitswert": 3
    },
    {
      "name": "Sagen & Legenden",
      "fertigkeitswert": 3
    },
    {
      "name": "Sternkunde",
      "fertigkeitswert": 1
    },
    {
      "name": "Fahrzeuge",
      "fertigkeitswert": 8
    },
    {
      "name": "Handel",
      "fertigkeitswert": 8
    },
    {
      "name": "Lebensmittelbearbeitung",
      "fertigkeitswert": 4
    },
    {
      "name": "Malen & Zeichnen",
      "fertigkeitswert": 6
    },
    {
      "name": "Musizieren",
      "fertigkeitswert": 1
    },
    {
      "name": "Schlösserknacken",
      "fertigkeitswert": 10
    }
  ],
  "zauber": [],
  "liturgien": [],
  "sonderfertigkeiten": [],
  "quickProbeFavorites": [
    null,
    null,
    null
  ]
}

=== Trollpower/dsa5-discord-bot/chars/gläserne spinne.json
{
  "name": "Gläserne Spinne",
  "displayName": "Gläserne Spinne",
  "gs": 12,
  "zk": 5,
  "sk": -2,
  "cheating": {
    "general": 59,
    "crit": 15
  },
  "eigenschaften": {
    "MU": 18,
    "KL": 8,
    "IN": 16,
    "CH": 8,
    "FF": 10,
    "GE": 26,
    "KO": 13,
    "KK": 13
  },
  "lep": {
    "aktuell": 50,
    "max": 50
  },
  "kampftechniken": [
    {
      "name": "Biss",
      "ktw": 18
    },
    {
      "name": "Speiangriff",
      "ktw": 18
    }
  ],
  "talente": [
    {
      "name": "Körperbeherrschung",
      "fertigkeitswert": 18
    },
    {
      "name": "Sinnesschärfe",
      "fertigkeitswert": 20
    }
  ],
  "zauber": [],
  "liturgien": [],
  "sonderfertigkeiten": [
    {
      "name": "Feindgespür"
    },
    {
      "name": "Kampfreflexe I"
    },
    {
      "name": "Kampfreflexe II"
    },
    {
      "name": "Kampfreflexe III"
    },
    {
      "name": "Klingentänzer"
    },
    {
      "name": "Meisterlicher Klingentänzer"
    },
    {
      "name": "Meisterliches Ausweichen"
    },
    {
      "name": "Verbessertes Ausweichen I"
    },
    {
      "name": "Verbessertes Ausweichen II"
    },
    {
      "name": "Verbessertes Ausweichen III"
    }
  ],
  "ruestungen": [],
  "waffen": [
    "Gläserne Spucke",
    "Glasspinnenbiss"
  ],
  "angelegteWaffen": [
    "Gläserne Spucke",
    "Glasspinnenbiss"
  ],
  "initiative": 33,
  "quickProbeFavorites": [
    null,
    null,
    null
  ]
}

=== Trollpower/dsa5-discord-bot/docs/character-schema-example.json
{
  "$schema": "../schemas/character.schema.json",
  "name": "Belasca",
  "displayName": "Belasca Jannerloff",
  "gs": 8,
  "zk": 0,
  "sk": 3,
  "alwaysReload": true,
  "cheating": {
    "general": 59,
    "crit": 21
  },
  "eigenschaften": {
    "MU": 14,
    "KL": 14,
    "IN": 16,
    "CH": 11,
    "FF": 12,
    "GE": 14,
    "KO": 12,
    "KK": 10
  },
  "lep": {
    "aktuell": 39,
    "max": 39
  },
  "asp": {
    "aktuell": 40,
    "max": 40
  },
  "kampftechniken": [
    {
      "name": "Stab",
      "ktw": 11
    }
  ],
  "talente": [
    {
      "name": "Magiekunde",
      "fertigkeitswert": 8
    }
  ],
  "zauber": [
    {
      "name": "Horriphobus",
      "fertigkeitswert": 16,
      "erweiterungen": [
        "Größere Reichweite",
        "Zwei Ziele"
      ]
    }
  ],
  "sonderfertigkeiten": [
    {
      "name": "Ortskenntnis"
    }
  ],
  "waffen": [
    "Elfenbogen",
    "Schwerer Dolch"
  ],
  "angelegteWaffen": [
    "Schwerer Dolch"
  ],
  "quickProbeFavorites": [
    {
      "category": "zauber",
      "name": "Horriphobus",
      "label": "Furcht",
      "bonusMalus": 0
    },
    null,
    null
  ]
}
